plugins:
  - name: etherscan
  - name: solidity
    version: 0.6.3
  - name: foundry

dependencies:
  - name: Aave
    github: aave/aave-v3-core
    version: 1.17.2
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.3

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.8.3"
    - "@aave=Aave/1.17.2"

ethereum:
  default_network: local
  local:
    default_provider: foundry

foundry:
  host: http://localhost:8555
