[workspace]

members = [
    "crates/fixed-point",
    "crates/fixed-point-macros",
    "crates/hyperdrive-addresses",
    "crates/hyperdrive-math",
    "crates/hyperdrive-wrappers",
    "crates/test-utils",
    "test/rust",
]
