[package]

name = "hyperdrive-math"
version = "0.1.0"
edition = "2021"

[dependencies]

ethers = "2.0"
eyre = "0.6.8"
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }

fixed-point = { version = "0.1.0", path = "../fixed-point" }
hyperdrive-wrappers = { version = "0.1.0", path = "../hyperdrive-wrappers" }
